# stored in file example_conf.yaml
name: pr_preview_config

global:
  TRAINED_ON: "Dummy data for preview"

data_manager:
  embedding_name: HuggingFaceEmbeddings
  embedding_class_map:
    HuggingFaceEmbeddings:
      class: HuggingFaceEmbeddings
      kwargs:
        model_name: sentence-transformers/all-MiniLM-L6-v2
        model_kwargs:
          device: cpu
        encode_kwargs:
          normalize_embeddings: true
      similarity_score_reference: 10
  chromadb_host: localhost  # Override default 'chromadb' for local testing
  use_hybrid_search: true
  input_lists:
    - configs/pr_preview_config/test_links.list

utils:
  sso:
    ENABLED: True
    SSO_CLASS: CERNSSOScraper
    SSO_CLASS_MAP:
      CERNSSOScraper:
        kwargs:
          headless: True # headless mode for scraping, as it is run in a container
          max_depth: 2 # max depth for crawling from starting URL

a2rchi:
  pipelines: ['QAPipeline']
  pipeline_map:
    QAPipeline:
      prompts:
        required:
          condense_prompt: configs/prompts/condense.prompt
          chat_prompt: configs/prompts/submit.prompt
      models:
        required:
          #condense_model: OpenAIGPT4
          #chat_model: OpenAIGPT4
          condense_model: DumbLLM
          chat_model: DumbLLM

interfaces:
  chat_app:
    EXTERNAL_PORT: 443
    HOSTNAME: vocms275.cern.ch
    enable_debug_chroma_endpoints : True
